# Generated by Django 4.2.11 on 2026-02-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.IntegerField(unique=True),
        ),
    ]
