# Generated by Django 4.2.11 on 2026-02-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcopy",
            options={"verbose_name_plural": "Book copies"},
        ),
        migrations.AlterModelOptions(
            name="borrowrecord",
            options={"ordering": ["-borrow_date"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
