# Generated by Django 4.2.11 on 2026-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_bookcopy_options_alter_borrowrecord_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.AddField(
            model_name="book",
            name="authors_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
